sudo: false

language: python
python:
  - "2.7"

cache: pip

services:
  - redis-server

install: 
 - cd ..
 - git clone --depth 1 https://github.com/Qabel/qabel.git
 - cd qabel
 - git submodule init
 - git submodule update --depth 1
 - rm -rf qabel-drop
 - mv ../qabel-drop ./
 - virtualenv qabel-drop 
 - source qabel-drop/bin/activate 
 - pip install -r qabel-drop/requirements.txt 
# command to run tests
script:
 - nosetests
 - travis_wait ./gradlew check
