# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_id', models.CharField(max_length=43)),
                ('message', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'created_at',
                'db_table': 'drops',
            },
            bases=(models.Model,),
        ),
    ]
